<a href="https://colab.research.google.com/github/Afrinnazir/Infosys-Springboard-Internship/blob/main/ISI_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hojjatk/mnist-dataset")

print("Path to dataset files:", path)

100%|██████████| 22.0M/22.0M [00:00<00:00, 133MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/hojjatk/mnist-dataset/versions/1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.29872078, -0.14797111,  1.0346272 , -0.23674092,  0.06910633,
        -0.8451414 ,  0.16120037, -0.572901  , -0.9731331 ,  0.3341993 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07256535, 0.08437213, 0.27529287, 0.07720524, 0.10482734,
        0.04201669, 0.11493982, 0.05516382, 0.03696883, 0.13664791]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

3.1696882

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8577 - loss: 0.4891
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9543 - loss: 0.1539
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9667 - loss: 0.1108
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9732 - loss: 0.0897
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9762 - loss: 0.0748


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9749 - loss: 0.0793


[0.07928300648927689, 0.9749000072479248]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.41610245e-07, 1.91071496e-08, 4.29798746e-07, 1.20057746e-04,
        1.10776111e-10, 3.33829888e-07, 2.10272731e-13, 9.99669671e-01,
        1.50257193e-08, 2.08640326e-04],
       [6.16018454e-08, 2.45383452e-03, 9.97463942e-01, 5.98509978e-05,
        2.46164866e-10, 7.62216757e-07, 2.69788870e-07, 6.56359522e-10,
        2.12881059e-05, 4.80854280e-11],
       [7.52675021e-07, 9.98180151e-01, 1.63792007e-04, 2.57900410e-05,
        9.41573671e-05, 2.72474153e-06, 8.43893213e-05, 7.75177672e-04,
        6.68761262e-04, 4.41706470e-06],
       [9.99967694e-01, 1.97915677e-11, 3.48291428e-06, 1.97184615e-08,
        5.18142649e-08, 2.65923813e-06, 2.18029763e-05, 1.09585051e-06,
        5.71712855e-09, 3.24375014e-06],
       [1.24370017e-05, 7.39625339e-09, 1.64059802e-05, 7.57905241e-08,
        8.64973724e-01, 2.72289617e-06, 1.58067705e-05, 2.80098739e-05,
        1.17559239e-06, 1.34949625e-01]], dtype=float32)>